# Generated by Django 3.1.2 on 2021-01-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_grocery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
