# Generated by Django 3.1.2 on 2021-01-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grocery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.grocery'),
        ),
    ]
