# Generated by Django 3.1.5 on 2021-01-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210109_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgrocery',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='productgrocery',
            name='pub_date',
        ),
    ]
