# Generated by Django 3.1.5 on 2021-01-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210122_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBakery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('grocery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.grocery')),
            ],
        ),
    ]
