# Generated by Django 3.1.5 on 2021-01-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bakery_productbakery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbakery',
            name='grocery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.bakery'),
        ),
    ]
