# Generated by Django 3.1.5 on 2021-01-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
