# Generated by Django 3.1.5 on 2021-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
