# Generated by Django 3.1.5 on 2021-01-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='productbakery',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='productgrocery',
            name='grocery',
        ),
        migrations.DeleteModel(
            name='Bakery',
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
        migrations.DeleteModel(
            name='ProductBakery',
        ),
        migrations.DeleteModel(
            name='ProductGrocery',
        ),
    ]
