# Generated by Django 3.1.5 on 2021-01-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
    ]
