# Generated by Django 3.1.5 on 2021-02-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_order_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_choice',
            field=models.CharField(choices=[('1', 'Cash on delivery'), ('2', 'Take away')], default=1, max_length=30),
        ),
    ]
