# Generated by Django 3.1.7 on 2021-03-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20210303_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
