# Generated by Django 3.1.7 on 2021-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_auto_20210303_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
